name: Test Project
on: push
jobs:
  test:
    runs-on: [macos-13]
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test
  lint:
    runs-on: [macos-13]
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lint
  build:
    runs-on: [macos-13]
    steps:
      - name: Create file
        run: echo "test" > file.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-files
          path: file.txt

  deploy:
    runs-on: [macos-13]
    needs: [test, lint]
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Install pod
        run: |
          cd ios && pod install

      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: test-files
